//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raflar
    {
        public int RafID { get; set; }
        public Nullable<int> KapladigiAlan { get; set; }
        public Nullable<int> DepoID { get; set; }
    
        public virtual Depolar Depolar { get; set; }
    }
}
