//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.UrunHareket = new HashSet<UrunHareket>();
            this.UrunHareket1 = new HashSet<UrunHareket>();
            this.UrunHareket2 = new HashSet<UrunHareket>();
        }
    
        public int UrunID { get; set; }
        public Nullable<int> DepoID { get; set; }
        public Nullable<int> RafID { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> UrunBoyutu { get; set; }
        public string UrunAgirligi { get; set; }
        public Nullable<int> UrunAdeti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunHareket> UrunHareket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunHareket> UrunHareket1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunHareket> UrunHareket2 { get; set; }
    }
}
